apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cj28exm5v-python 
  janus-idp.io/tekton: cj28exm5v-python
  backstage.io/kubernetes-id: cj28exm5v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cj28exm5v-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  