apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cj28exm5v-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cj28exm5v-python 
  name: cj28exm5v-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cj28exm5v-python 
